name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Export static files (if needed)
      run: npm run export || true

    - name: Deploy to Vercel
      if: vars.VERCEL_TOKEN != ''
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
        vercel-project-id: ${{ vars.VERCEL_PROJECT_ID }}
        working-directory: .

    - name: Deploy to Netlify (alternative)
      if: vars.NETLIFY_SITE_ID != ''
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=.next
      env:
        NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Deploy to GitHub Pages
      if: vars.USE_GITHUB_PAGES == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    environment:
      name: staging
      url: ${{ vars.STAGING_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Deploy to Vercel (Preview)
      if: vars.VERCEL_TOKEN != ''
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
        vercel-project-id: ${{ vars.VERCEL_PROJECT_ID }}
        working-directory: .

    - name: Deploy to Netlify (Preview)
      if: vars.NETLIFY_SITE_ID != ''
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=.next
      env:
        NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}